# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

language: php

sudo: false

php:
    - '7.1'
    - '7.2'

before_install:
    - composer self-update
    - pecl install ast
    - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install --prefer-source --no-interaction

script:
    - ./vendor/bin/phpunit

matrix:
    fast_finish: true
    allow_failures:
        - php : nightly